### PR TITLE
Fixed extension as crossref.org api changed.

### PR DESCRIPTION
**Pull request by davidteather**
The crossref.org api changed and I've now fixed it.

### CODE REVIEW

**Comment by rayset** [comment]
hi, just a minor fix:
I had to fix the link to doi2bib so that it includes the "www".

Other than that great job and thanks :)

**Comment by sgrieve** [comment]
Hi @davidteather and @rayset, thank you so much for your help getting this fixed! I have been swamped lately and have not had the time to look at this until now.

The fixes look great and everything is working perfectly again on my end.

**Review by sgrieve — APPROVED** [review]

**Comment by sgrieve** [comment]
@all-contributors please add rayset for review

@all-contributors please add davidteather for code and maintenance

**Comment by sgrieve** [comment]
@all-contributors please add @rayset for review

@all-contributors please add @davidteather for code and maintenance

**Comment by sgrieve** [comment]
@all-contributors please add rayset for review

**Comment by sgrieve** [comment]
@all-contributors please add davidteather for code and maintenance

**Comment by sgrieve** [comment]
@all-contributors please add rayset for review

**Pull request merged**
